export type Accent = "amber" | "violet" | "teal" | "pink";

export type Plan = {
  id: string;
  name: string;
  price?: string;
  originalPrice?: string;
  period?: string;
  note?: string;
  badge?: string;
  cta?: string;
  accent: Accent;
  comingSoon?: boolean;
  included?: boolean;
  tagline?: string;
};

export const APP_STORE =
  "https://apps.apple.com/gb/app/pocket-squats/id6748518785";

export const FEATURES = [
  "Personalized workout programs generated by AI",
  "Live workouts with exercise tracking",
  "Calendar and scheduling capabilities",
  "Advanced analytics including body weight and exercise progression",
  "AI Personal Coach support",
  "Nutrition & meal tracking (Food) - included free while we launch",
];

// what the bundled Food membership unlocks (shown on the Food card)
export const FOOD_FEATURES = [
  "Snap a photo or scan a barcode to log a meal",
  "AI macro estimates - protein, carbs and fat",
  "Daily targets matched to your training, no red numbers",
  "Included with every workout membership - no separate purchase",
];

export const PLANS: Plan[] = [
  {
    id: "yearly",
    name: "Yearly",
    price: "$59.99",
    period: "/ year",
    note: "Save 50% vs paying monthly - that's $119.88/year at $9.99/mo. £59.99 / €59.99",
    badge: "Save 50%",
    cta: "Get Started",
    accent: "amber",
  },
  {
    id: "monthly",
    name: "Monthly",
    price: "$9.99",
    period: "/ mo",
    note: "£9.99 / €9.99",
    badge: "Flexible",
    cta: "Join now",
    accent: "violet",
  },
  {
    id: "food",
    name: "Food",
    accent: "teal",
    included: true,
    badge: "New",
    cta: "Get Started",
    tagline:
      "AI-powered nutrition and meal tracking, built to match your training. For a limited time it's bundled with every Pocket Fit workout membership - unlock workouts and Food comes with it, no separate purchase.",
  },
  {
    id: "hardcore",
    name: "Hardcore",
    accent: "pink",
    comingSoon: true,
    tagline:
      "Elite, high-intensity programming for serious lifters who want to be pushed. Coming soon to Pocket Fit.",
  },
];
